In [3]:
import pandas as pd  
import numpy as np 
# Series: a one-dimensional labeled array holding data of any type
# such as integers, strings, Python objects etc.

# DataFrame: a two-dimensional data structure that holds data like a two-dimension array or a table with rows and columns.

s = pd.Series([1,23,4,np.nan,8,9])
s

0     1.0
1    23.0
2     4.0
3     NaN
4     8.0
5     9.0
dtype: float64

In [ ]:
#  NumPy array with a datetime index using date_range()

dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [6]:
df =  pd.DataFrame(np.random.randn(6,4),index=dates,columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01 -0.122419 -0.619337  0.842833  1.568250
2013-01-02  1.323666  1.297615 -0.421852  0.814174
2013-01-03 -0.163157  0.832602 -1.079639  0.166534
2013-01-04 -0.228633 -0.331293  0.098116 -0.702801
2013-01-05  2.395792 -1.592562 -0.574741  0.405998
2013-01-06  1.047617 -0.248579  1.259807 -0.842220

In [18]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [21]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [24]:
# view data 
df.head()
df.tail(3)

                   A         B         C         D
2013-01-04 -0.228633 -0.331293  0.098116 -0.702801
2013-01-05  2.395792 -1.592562 -0.574741  0.405998
2013-01-06  1.047617 -0.248579  1.259807 -0.842220

In [25]:
df.tail(3)

                   A         B         C         D
2013-01-04 -0.228633 -0.331293  0.098116 -0.702801
2013-01-05  2.395792 -1.592562 -0.574741  0.405998
2013-01-06  1.047617 -0.248579  1.259807 -0.842220

In [26]:
df.index

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [27]:
df.to_numpy()

array([[-0.12241922, -0.61933745,  0.84283283,  1.5682501 ],
       [ 1.32366568,  1.29761507, -0.4218522 ,  0.81417371],
       [-0.1631566 ,  0.83260162, -1.0796388 ,  0.16653364],
       [-0.22863287, -0.33129297,  0.0981162 , -0.70280058],
       [ 2.39579238, -1.59256158, -0.57474106,  0.405998  ],
       [ 1.04761717, -0.24857937,  1.25980694, -0.84222038]])

In [28]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.708811 -0.110259  0.020754  0.234989
std    1.064783  1.038794  0.892012  0.915074
min   -0.228633 -1.592562 -1.079639 -0.842220
25%   -0.152972 -0.547326 -0.536519 -0.485467
50%    0.462599 -0.289936 -0.161868  0.286266
75%    1.254654  0.562306  0.656654  0.712130
max    2.395792  1.297615  1.259807  1.568250

In [29]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -0.122419    1.323666   -0.163157   -0.228633    2.395792    1.047617
B   -0.619337    1.297615    0.832602   -0.331293   -1.592562   -0.248579
C    0.842833   -0.421852   -1.079639    0.098116   -0.574741    1.259807
D    1.568250    0.814174    0.166534   -0.702801    0.405998   -0.842220

In [30]:
df.sort_values(by="B")

                   A         B         C         D
2013-01-05  2.395792 -1.592562 -0.574741  0.405998
2013-01-01 -0.122419 -0.619337  0.842833  1.568250
2013-01-04 -0.228633 -0.331293  0.098116 -0.702801
2013-01-06  1.047617 -0.248579  1.259807 -0.842220
2013-01-03 -0.163157  0.832602 -1.079639  0.166534
2013-01-02  1.323666  1.297615 -0.421852  0.814174

In [ ]:
# Getitem ([])

df["B"].sort_values()

2013-01-05   -1.592562
2013-01-01   -0.619337
2013-01-04   -0.331293
2013-01-06   -0.248579
2013-01-03    0.832602
2013-01-02    1.297615
Name: B, dtype: float64

In [36]:
df[["B","A"]]

                   B         A
2013-01-01 -0.619337 -0.122419
2013-01-02  1.297615  1.323666
2013-01-03  0.832602 -0.163157
2013-01-04 -0.331293 -0.228633
2013-01-05 -1.592562  2.395792
2013-01-06 -0.248579  1.047617

In [37]:
# Selection by label

df.loc[dates[0]]

A   -0.122419
B   -0.619337
C    0.842833
D    1.568250
Name: 2013-01-01 00:00:00, dtype: float64

In [39]:
df[0:3]

                   A         B         C         D
2013-01-01 -0.122419 -0.619337  0.842833  1.568250
2013-01-02  1.323666  1.297615 -0.421852  0.814174
2013-01-03 -0.163157  0.832602 -1.079639  0.166534

In [40]:
# Selection by label

df.loc[:,["A","B"]]

                   A         B
2013-01-01 -0.122419 -0.619337
2013-01-02  1.323666  1.297615
2013-01-03 -0.163157  0.832602
2013-01-04 -0.228633 -0.331293
2013-01-05  2.395792 -1.592562
2013-01-06  1.047617 -0.248579

In [41]:
df.loc["20130102":"20130104", ["A", "B"]]

                   A         B
2013-01-02  1.323666  1.297615
2013-01-03 -0.163157  0.832602
2013-01-04 -0.228633 -0.331293

In [43]:
# Boolean indexing

df[df["A"] > 0 ]

                   A         B         C         D
2013-01-02  1.323666  1.297615 -0.421852  0.814174
2013-01-05  2.395792 -1.592562 -0.574741  0.405998
2013-01-06  1.047617 -0.248579  1.259807 -0.842220

In [44]:
df[df>0]

                   A         B         C         D
2013-01-01       NaN       NaN  0.842833  1.568250
2013-01-02  1.323666  1.297615       NaN  0.814174
2013-01-03       NaN  0.832602       NaN  0.166534
2013-01-04       NaN       NaN  0.098116       NaN
2013-01-05  2.395792       NaN       NaN  0.405998
2013-01-06  1.047617       NaN  1.259807       NaN

In [47]:
df2 = df.copy()
df2["E"] =  ["one", "one", "two", "three", "four", "three"]

df2

                   A         B         C         D      E
2013-01-01 -0.122419 -0.619337  0.842833  1.568250    one
2013-01-02  1.323666  1.297615 -0.421852  0.814174    one
2013-01-03 -0.163157  0.832602 -1.079639  0.166534    two
2013-01-04 -0.228633 -0.331293  0.098116 -0.702801  three
2013-01-05  2.395792 -1.592562 -0.574741  0.405998   four
2013-01-06  1.047617 -0.248579  1.259807 -0.842220  three

In [48]:
df2[df2["E"].isin(["two" ,"four"])]

                   A         B         C         D     E
2013-01-03 -0.163157  0.832602 -1.079639  0.166534   two
2013-01-05  2.395792 -1.592562 -0.574741  0.405998  four

In [61]:
# Setting
# Setting a new column automatically aligns the data by the indexes::

s1 = pd.Series([1,2,3,4,5,6],index = pd.date_range("20130102" , periods=6))
s1

2013-01-02    1
2013-01-03    2
2013-01-04    3
2013-01-05    4
2013-01-06    5
2013-01-07    6
Freq: D, dtype: int64

In [74]:
df.head()

                   A         B         C    D    F
2013-01-01  0.000000  0.000000  0.842833  5.0  NaN
2013-01-02  1.323666  1.297615 -0.421852  5.0  1.0
2013-01-03 -0.163157  0.832602 -1.079639  5.0  2.0
2013-01-04 -0.228633 -0.331293  0.098116  5.0  3.0
2013-01-05  2.395792 -1.592562 -0.574741  5.0  4.0

In [73]:
df["F"] = s1 
# Setting values by label:
df.at[dates[0],"A"] = 0 
# Setting values by position:
df.iat[0,1] = 0 
# Setting by assigning with a NumPy array:
df.loc[: , "D"] = np.array([5]*len(df))

In [65]:
df

                   A         B         C    D    F
2013-01-01  0.000000  0.000000  0.842833  5.0  NaN
2013-01-02  1.323666  1.297615 -0.421852  5.0  1.0
2013-01-03 -0.163157  0.832602 -1.079639  5.0  2.0
2013-01-04 -0.228633 -0.331293  0.098116  5.0  3.0
2013-01-05  2.395792 -1.592562 -0.574741  5.0  4.0
2013-01-06  1.047617 -0.248579  1.259807  5.0  5.0

In [ ]:
df1 = df.reindex()

                   A         B         C         D      E
2013-01-01 -0.122419 -0.619337  0.842833  1.568250    one
2013-01-02  1.323666  1.297615 -0.421852  0.814174    one
2013-01-03 -0.163157  0.832602 -1.079639  0.166534    two
2013-01-04 -0.228633 -0.331293  0.098116 -0.702801  three
2013-01-05  2.395792 -1.592562 -0.574741  0.405998   four
2013-01-06  1.047617 -0.248579  1.259807 -0.842220  three