In [81]:
import pandas as pd 
import numpy as np 

df = pd.DataFrame({
    "name":   ["Asha", "Ben", "Chitra", "Dev", "Esha", "Farid"],
    "age":    [25, 32, 28, 45, 38, 29],
    "city":   ["Mumbai", "Delhi", "Pune", "Mumbai", "Pune", "Delhi"],
    "salary": [50000, 72000, 61000, 120000, 98000, 58000],
    "dept":   ["IT", "HR", "IT", "Finance", "IT", "HR"],
})

In [82]:
pd.DataFrame([{"a": 1, "b": 2}, {"a": 3, "c": 4}])

   a    b    c
0  1  2.0  NaN
1  3  NaN  4.0

In [83]:
pd.DataFrame(np.arange(6).reshape(2, 3), columns=list("ABC"), index=["r1", "r2"])

    A  B  C
r1  0  1  2
r2  3  4  5

In [84]:
df.head(3)

     name  age    city  salary dept
0    Asha   25  Mumbai   50000   IT
1     Ben   32   Delhi   72000   HR
2  Chitra   28    Pune   61000   IT

In [85]:
df.tail(3)

    name  age    city  salary     dept
3    Dev   45  Mumbai  120000  Finance
4   Esha   38    Pune   98000       IT
5  Farid   29   Delhi   58000       HR

In [86]:
print(df.sample(2,random_state=1))

     name  age   city  salary dept
2  Chitra   28   Pune   61000   IT
1     Ben   32  Delhi   72000   HR

In [87]:
print(df.columns.tolist())

['name', 'age', 'city', 'salary', 'dept']

In [88]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      str
 1   age     6 non-null      int64
 2   city    6 non-null      str
 3   salary  6 non-null      int64
 4   dept    6 non-null      str
dtypes: int64(2), str(3)
memory usage: 444.0 bytes

In [89]:
df.describe()

             age         salary
count   6.000000       6.000000
mean   32.833333   76500.000000
std     7.413951   27053.650401
min    25.000000   50000.000000
25%    28.250000   58750.000000
50%    30.500000   66500.000000
75%    36.500000   91500.000000
max    45.000000  120000.000000

In [90]:
df

     name  age    city  salary     dept
0    Asha   25  Mumbai   50000       IT
1     Ben   32   Delhi   72000       HR
2  Chitra   28    Pune   61000       IT
3     Dev   45  Mumbai  120000  Finance
4    Esha   38    Pune   98000       IT
5   Farid   29   Delhi   58000       HR

In [91]:
print(df.describe(include="all"))

        name        age    city         salary dept
count      6   6.000000       6       6.000000    6
unique     6        NaN       3            NaN    3
top     Asha        NaN  Mumbai            NaN   IT
freq       1        NaN       2            NaN    3
mean     NaN  32.833333     NaN   76500.000000  NaN
std      NaN   7.413951     NaN   27053.650401  NaN
min      NaN  25.000000     NaN   50000.000000  NaN
25%      NaN  28.250000     NaN   58750.000000  NaN
50%      NaN  30.500000     NaN   66500.000000  NaN
75%      NaN  36.500000     NaN   91500.000000  NaN
max      NaN  45.000000     NaN  120000.000000  NaN

In [92]:
print(df["city"].nunique())
print(df["city"].unique())

3
<ArrowStringArray>
['Mumbai', 'Delhi', 'Pune']
Length: 3, dtype: str

In [93]:
print(df.dtypes)

name        str
age       int64
city        str
salary    int64
dept        str
dtype: object

In [94]:
print(df["name"].head(2))

0    Asha
1     Ben
Name: name, dtype: str

In [95]:
print(df[["name","salary"]].head(2))

   name  salary
0  Asha   50000
1   Ben   72000

In [96]:
df

     name  age    city  salary     dept
0    Asha   25  Mumbai   50000       IT
1     Ben   32   Delhi   72000       HR
2  Chitra   28    Pune   61000       IT
3     Dev   45  Mumbai  120000  Finance
4    Esha   38    Pune   98000       IT
5   Farid   29   Delhi   58000       HR

In [97]:
print(df.loc[0:2 , ["name","age"]])
print(df.iloc[0:2 , 0:2])

print(df.iloc[-1])
print(df.at[1,"name"],df.iat[1,0])

     name  age
0    Asha   25
1     Ben   32
2  Chitra   28
   name  age
0  Asha   25
1   Ben   32
name      Farid
age          29
city      Delhi
salary    58000
dept         HR
Name: 5, dtype: object
Ben Ben

In [98]:
print(df[df["salary"] > 60000])

     name  age    city  salary     dept
1     Ben   32   Delhi   72000       HR
2  Chitra   28    Pune   61000       IT
3     Dev   45  Mumbai  120000  Finance
4    Esha   38    Pune   98000       IT

In [99]:
print(df[(df["age"]>28) & (df["city"] == "Pune")])

   name  age  city  salary dept
4  Esha   38  Pune   98000   IT

In [100]:
print(df[df["city"].isin(["Pune","Delhi"])])

     name  age   city  salary dept
1     Ben   32  Delhi   72000   HR
2  Chitra   28   Pune   61000   IT
4    Esha   38   Pune   98000   IT
5   Farid   29  Delhi   58000   HR

In [101]:
print(df[df["age"].between(28,38)])

     name  age   city  salary dept
1     Ben   32  Delhi   72000   HR
2  Chitra   28   Pune   61000   IT
4    Esha   38   Pune   98000   IT
5   Farid   29  Delhi   58000   HR

In [102]:
print(df[~df["dept"].eq("IT")])

    name  age    city  salary     dept
1    Ben   32   Delhi   72000       HR
3    Dev   45  Mumbai  120000  Finance
5  Farid   29   Delhi   58000       HR

In [103]:
d = df.copy()

In [104]:
d

     name  age    city  salary     dept
0    Asha   25  Mumbai   50000       IT
1     Ben   32   Delhi   72000       HR
2  Chitra   28    Pune   61000       IT
3     Dev   45  Mumbai  120000  Finance
4    Esha   38    Pune   98000       IT
5   Farid   29   Delhi   58000       HR

In [ ]:
d["bonus"] = d["salary"]*0.1
d["tax"] = np.where(d["salary"] > 70000 ,0.3,0.2)*d["salary"]
d = d.assign(net = lambda x : x["salary"] - x["tax"])
d.loc[d["name"] == "Ben" ,"age"] = 33
d.insert(1 ,"id" ,range(100,106))
print(d)

     name   id  age    city  salary     dept    bonus      tax      net
0    Asha  100   25  Mumbai   50000       IT   5000.0  10000.0  40000.0
1     Ben  101   33   Delhi   72000       HR   7200.0  21600.0  50400.0
2  Chitra  102   28    Pune   61000       IT   6100.0  12200.0  48800.0
3     Dev  103   45  Mumbai  120000  Finance  12000.0  36000.0  84000.0
4    Esha  104   38    Pune   98000       IT   9800.0  29400.0  68600.0
5   Farid  105   29   Delhi   58000       HR   5800.0  11600.0  46400.0