In [1]:
import numpy as np 
import pandas as pd

In [2]:
a1 = np.array([5,9,8,3,9,1,2,7])
type(a1)
a1>=4

array([ True,  True,  True, False,  True, False, False,  True])

In [4]:
type(a1)

numpy.ndarray

In [ ]:
t1 = np.where(a1>=4)  # remember this is use ver ofently in data analyis 
print(t1)
print(len(t1))
print(len(t1[0]))
print(a1[t1]) # this is only posible with array it not possibel in list  
print((a1>=4).sum()) # how many are thair meet the condtions

(array([0, 1, 2, 4, 7]),)
1
5
[5 9 8 9 7]
5

In [ ]:
# Q1 where are the value which meets the codntions 
#-> t1 = np.where(a1>=4)
#Q2 what are the value which meet a condions 
#->a1[t1]
#Q3 how many value meet the perticular condtions 
#->len(t1[0])

In [14]:
import os 
os.getcwd()  # give current working diretory\

'c:\\Users\\praja\\Data-Analytics\\02. Numpy and Pandas'

In [15]:
os.chdir('C:\\Users\\praja\\Downloads')

In [16]:
os.getcwd()

'C:\\Users\\praja\\Downloads'

In [31]:
df = pd.read_excel('CDAC_DataBook.xlsx',sheet_name='ERPData') # it give data frame in ERPdata only

In [32]:
df

   MaterialID Location  Quantity
0     TMI-43T    MWH-4        34
1     AXCP-78    MWH-1        67
2     LXCV-21    MWH-2        27
3     AXCP-78    MWH-5        65
4     AXCP-78    MWH-4        36
5     TMI-43T    MWH-4        78
6     TMI-43T    MWH-4        31
7     TMI-43T    MWH-2        29
8     GCVB-79    MWH-2        10
9     TMI-43T    MWH-1       120
10    SDRT-67    MWH-1        34
11    SDRT-67    MWH-4        58
12    TMI-43T    MWH-4        76
13    TMI-43T    MWH-4        32
14    TMI-43T    MWH-3        65
15    GCVB-79    MWH-2        87
16    SDRT-67    MWH-5        12
17    SDRT-67    MWH-5       102
18    TMI-43T    MWH-4        34
19    TMI-43T    MWH-4        52
20    TMI-43T    MWH-4        39
21    TMI-43T    MWH-4        75
22    DDBN-89    MWH-4        48
23    DDBN-89    MWH-5        71
24    AXCP-78    MWH-1       152
25    AXCP-78    MWH-1       109
26    DDBN-89    MWH-1        57
27    LXCV-21    MWH-5        83
28    LXCV-21    MWH-5        34
29    LXCV-21    MWH-5        57
30    DDBN-89    MWH-4        27
31    TMI-43T    MWH-4        65
32    TMI-43T    MWH-4        43
33    TMI-43T    MWH-5       112
34    GCVB-79    MWH-5        26
35    GCVB-79    MWH-2        31
36    GCVB-79    MWH-2        28
37    AXCP-78    MWH-5        65
38    AXCP-78    MWH-5        70
39    AXCP-78    MWH-1       145
40    DDBN-89    MWH-1        34
41    SDRT-67    MWH-1        57
42    SDRT-67    MWH-2        31
43    DDBN-89    MWH-3        38
44    LXCV-21    MWH-3        42
45    DDBN-89    MWH-2        69
46    AXCP-78    MWH-2        85
47    AXCP-78    MWH-3        29
48    AXCP-78    MWH-1        75
49    DDBN-89    MWH-1        39

In [33]:
x1 = df.Quantity#
print(x1)

0      34
1      67
2      27
3      65
4      36
5      78
6      31
7      29
8      10
9     120
10     34
11     58
12     76
13     32
14     65
15     87
16     12
17    102
18     34
19     52
20     39
21     75
22     48
23     71
24    152
25    109
26     57
27     83
28     34
29     57
30     27
31     65
32     43
33    112
34     26
35     31
36     28
37     65
38     70
39    145
40     34
41     57
42     31
43     38
44     42
45     69
46     85
47     29
48     75
49     39
Name: Quantity, dtype: int64

In [34]:
type(x1)

pandas.Series

In [37]:
sum(x1)

2885

In [38]:
(df.Quantity>=80).sum()

np.int64(9)

In [ ]:
len(np.where(df.Quantity>=80)[0])

9

In [48]:
np.where(df.Quantity == max(df.Quantity))

(array([24]),)

In [49]:
df.Location[np.where(df.Quantity == max(df.Quantity))[0]]

24    MWH-1
Name: Location, dtype: str

In [50]:
np.where(df.Quantity == max(df.Quantity))[0]

array([24])

In [51]:
df.head()

  MaterialID Location  Quantity
0    TMI-43T    MWH-4        34
1    AXCP-78    MWH-1        67
2    LXCV-21    MWH-2        27
3    AXCP-78    MWH-5        65
4    AXCP-78    MWH-4        36

In [52]:
np.unique(df.MaterialID)

array(['AXCP-78', 'DDBN-89', 'GCVB-79', 'LXCV-21', 'SDRT-67', 'TMI-43T'],
      dtype=object)

In [53]:
np.unique(df.Location)

array(['MWH-1', 'MWH-2', 'MWH-3', 'MWH-4', 'MWH-5'], dtype=object)

In [64]:
#GoupBy Cammand is only usededd in categoricacl data 
#grouping can be done in multiple colums 
grp1 = df.groupby('Location')
grp2 = df.groupby('MaterialID')
grp3 = df.groupby(['MaterialID' ,'Location'])
grp4 = df.groupby(['Location','MaterialID'])
grp1.Quantity.agg(['sum' ,'mean' ,'size'])

          sum       mean  size
Location
MWH-1     889  80.818182    11
MWH-2     397  44.111111     9
MWH-3     174  43.500000     4
MWH-4     728  48.533333    15
MWH-5     697  63.363636    11

In [65]:
grp2.Quantity.agg(['sum','mean','size'])

            sum       mean  size
MaterialID
AXCP-78     898  81.636364    11
DDBN-89     383  47.875000     8
GCVB-79     182  36.400000     5
LXCV-21     243  48.600000     5
SDRT-67     294  49.000000     6
TMI-43T     885  59.000000    15

In [66]:
grp3.Quantity.agg(['sum','mean','size'])

                     sum        mean  size
MaterialID Location
AXCP-78    MWH-1     548  109.600000     5
           MWH-2      85   85.000000     1
           MWH-3      29   29.000000     1
           MWH-4      36   36.000000     1
           MWH-5     200   66.666667     3
DDBN-89    MWH-1     130   43.333333     3
           MWH-2      69   69.000000     1
           MWH-3      38   38.000000     1
           MWH-4      75   37.500000     2
           MWH-5      71   71.000000     1
GCVB-79    MWH-2     156   39.000000     4
           MWH-5      26   26.000000     1
LXCV-21    MWH-2      27   27.000000     1
           MWH-3      42   42.000000     1
           MWH-5     174   58.000000     3
SDRT-67    MWH-1      91   45.500000     2
           MWH-2      31   31.000000     1
           MWH-4      58   58.000000     1
           MWH-5     114   57.000000     2
TMI-43T    MWH-1     120  120.000000     1
           MWH-2      29   29.000000     1
           MWH-3      65   65.000000     1
           MWH-4     559   50.818182    11
           MWH-5     112  112.000000     1

In [71]:
df1= grp4.Quantity.agg(['sum','mean','size'])
df1

                     sum        mean  size
Location MaterialID
MWH-1    AXCP-78     548  109.600000     5
         DDBN-89     130   43.333333     3
         SDRT-67      91   45.500000     2
         TMI-43T     120  120.000000     1
MWH-2    AXCP-78      85   85.000000     1
         DDBN-89      69   69.000000     1
         GCVB-79     156   39.000000     4
         LXCV-21      27   27.000000     1
         SDRT-67      31   31.000000     1
         TMI-43T      29   29.000000     1
MWH-3    AXCP-78      29   29.000000     1
         DDBN-89      38   38.000000     1
         LXCV-21      42   42.000000     1
         TMI-43T      65   65.000000     1
MWH-4    AXCP-78      36   36.000000     1
         DDBN-89      75   37.500000     2
         SDRT-67      58   58.000000     1
         TMI-43T     559   50.818182    11
MWH-5    AXCP-78     200   66.666667     3
         DDBN-89      71   71.000000     1
         GCVB-79      26   26.000000     1
         LXCV-21     174   58.000000     3
         SDRT-67     114   57.000000     2
         TMI-43T     112  112.000000     1

In [ ]:
df2 = df1.loc['MWH-1']

            sum        mean  size
MaterialID
AXCP-78     548  109.600000     5
DDBN-89     130   43.333333     3
SDRT-67      91   45.500000     2
TMI-43T     120  120.000000     1